{% set name = "dggrid" %}
{% set version = "7.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/allixender/DGGRID/archive/refs/tags/v{{ version }}-conda2.tar.gz
  sha256: 195bd13452b8fad0188e1ae5a2adb2e5dcd2d62e7a403c391fcb678d32bcb98a

build:
  number: 0

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake >=3.12,<4
    - make  # [not win]
    - ninja  # [win]
  host:
    - libgdal
    - shapelib
  run:
    - libgdal
    - shapelib

test:
  commands:
    - test -f ${PREFIX}/bin/dggrid
    - if not exist %LIBRARY_BIN%\dggrid exit 1  # [win]

about:
  home: https://github.com/sahrk/DGGRID
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: A command-line application that generates and manipulates icosahedral discrete global grids.

  dev_url: https://github.com/sahrk/DGGRID

extra:
  recipe-maintainers:
    - allixender
