{% set name = "dggrid" %}
{% set version = "8.1b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/allixender/DGGRID/archive/refs/tags/v{{ version }}-conda3.tar.gz
  sha256: 3531e0248f94a90e32deb78b57b9d8e4376870dcfc20698ff2acf5074606f3ba

build:
  number: 2

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake >=3.19,<4
    - make  # [not win]
    - ninja  # [win]
  host:
    - libgdal
    - shapelib
  run:
    - libgdal
    - shapelib

test:
  commands:
    - dggrid -v
    - dggrid.exe -v  # [win]

about:
  home: https://github.com/sahrk/DGGRID
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: A command-line application that generates and manipulates icosahedral discrete global grids.

  dev_url: https://github.com/sahrk/DGGRID

extra:
  recipe-maintainers:
    - allixender
